### ISSUE TITLE
Loss

### ISSUE THREAD

**Issue by songyadong106** [NVIDIA/semantic-segmentation#18]
您好，最近在看这篇文章，其中Label Relaxation觉得很有用，想把文章中Label Relaxation部分拿过来用，自己之前用的是交叉熵损失函数，今天试了试您的ImgWtLossSoftNLL,却报错了，input[1,3,480,640],target[1,480,640],我用这两种输入测试的，您可不可以具体说一下您的的loss使用方法，很感谢，在线等！

**Comment by bryanyzhu** [comment]
Could you please attach the error message? Otherwise it's hard to find what caused the error.

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/62998388-f4570f80-be9d-11e9-9f6c-1eabb522454e.png)


if __name__ == '__main__':
    inputs=torch.rand(1,3,480, 640).to("cuda")
    outputs=torch.rand(1,480,640).to("cuda")
    criterion =  ImgWtLossSoftNLL()
    a = criterion(inputs,outputs)

错误：
weights = target[:, :-1, :, :].sum(1).float()
IndexError: too many indices for tensor of dimension 3

**Comment by songyadong106** [comment]
I want to know how many dimensions are your target?

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/63000233-3cc4fc00-bea3-11e9-8944-96fee62eb97d.png)
就是不太清楚代码的forward(self, inputs, target)  输入都是什么格式，谢谢了1

**Comment by bryanyzhu** [comment]
Hi @songyadong106, in your case, the dimension of the target will be `1x20x480x640`. `20 is 19 + 1`, because Cityscapes has 19 classes. You can read this function [RelaxedBoundaryLossToTensor](https://github.com/NVIDIA/semantic-segmentation/blob/master/transforms/transforms.py#L74) for more details, to see how we transform a `480x640` mask to `20x480x640`.

**Comment by bryanyzhu** [comment]
This issue is **how to use label relaxation loss for other problems/data. What is the dimension of the input image and input mask?** If they simply use `input[1,3,480,640]` and `target[1,480,640]` as in standard cross-entropy loss, it won't work with the `ImgWtLossSoftNLL` function. 

Solution: The input to our network is `input[1,3,480,640]` and `target[1,num_class+1,480,640]`.  In Cityscapes case, there are 19 classes, so the dimension of the target will be `[1,20,480,640]`. For more details, you can read function [RelaxedBoundaryLossToTensor](https://github.com/NVIDIA/semantic-segmentation/blob/master/transforms/transforms.py#L74) to see how we transform a `480x640` mask to `20x480x640`.

**Comment by songyadong106** [comment]
非常感谢您的回复，还有一个问题是：我做的是图像分割(3 类别)，背景对应的mask:0,如果背景也参与loss计算，那么ignore_id=0？，class =2(RelaxedBoundaryLossToTensor(0,2))

**Comment by bryanyzhu** [comment]
不好意思, 你是说背景参与还是不参与? 如果不参与的话, 对的, ignore_id=0, class =2. 但如果背景也参与loss计算, 那ignore_id不用设定, class=3.

**Comment by songyadong106** [comment]
是的，背景需要参加计算，对于正常的cross_entropy来说，比如我做的是图像分割三分类，我模型输出是[bach_size,3,480,640],对应的target:[batch_size,480,640]这个是正常操作（target我用的是.npy文件-【0，1，2】），现在我想用你的loss,还是三分类，模型输出依然是[bach_size,3,480,640]，target是把.npy用transform.转换成[batch_size,3,480,640]吗？   还是说把上面的.png图转换成[batch_size,3,480,640]？

**Comment by bryanyzhu** [comment]
哦, 那如果背景需要参加计算, 那num_class已经是3了. 所以你需要用transform把.npy变成[batch_size, num_class+1, 480,640], 也就是[batch_size,4,480,640].

**Comment by songyadong106** [comment]
包括背景我是三分类[groundtruth:0, tooth:1, palatal:2],我想让他们都参与计算，也就是说(RelaxedBoundaryLossToTensor(0,2))？

**Comment by bryanyzhu** [comment]
应该是 ``RelaxedBoundaryLossToTensor(ignore_id=-1, num_classes=3)``

因为你是三分类, 所以num_class=3. 

因为你要考虑ground truth, 所以不能把ignore_id设成0, 否则背景类就被忽略了. 设成任何一个不是0,1,2的数字都行, 比如-1.

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/63074748-46149e00-bf61-11e9-8ffe-493f54f23aaf.png)
我按照你说的去做了，结果还是生成了一个[4,480,640],按道理来说，我的.npy中出现了[0,1,2]，最后三分类不应该是[3,480,640]？

**Comment by bryanyzhu** [comment]
对的, 你生成[4,480,640]就对了. 我们relax loss需要的target输入就是[1,4,480,640]. 

你现在如果用`ImgWtLossSoftNLL`的话, 应该是不会报错了.

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/63075858-a6a5da00-bf65-11e9-8c97-c722ef1517ba.png)
不好意思了，您看一下我的输入格式有问题吗，仍然报错!

**Comment by bryanyzhu** [comment]
这个不是输入格式的问题了. 报错信息很明显. numpy ndarray没有`unsqueeze`这个function. 你传进去的东西应该是torch tensor才行. 就是说你的Img和gt要是tensor, 不能是numpy.

**Comment by songyadong106** [comment]
非常感谢您的帮助，loss部分已经解决了，我看了看评估函数，不是很明白您的miou是怎么设计的，毕竟您的target变成了【1，4，480，640】，模型预测是【1，3，480，640】，target的转换是可以理解为了重新定义loss，那么训练过程中的衡量指标也是通过设计后的target得到的吗？

**Comment by bryanyzhu** [comment]
请问你看的是哪里的评估函数, 最好给个链接. 我们还是用的正常的miou当做evaluation metric. 

1. target的转换就是为了重新定义loss, 帮助模型更好的训练.

2. 我们validate的过程中, 用的是普通的cross-entropy loss. 请看[这里](https://github.com/NVIDIA/semantic-segmentation/blob/master/train.py#L159), 我们train和validate的criterion是不一样的. 

3. 至于evaluation metric, 我们就是用的standard的mIoU, 没有改变.

**Comment by karansapra** [comment]
Closing the issue, please let us know if we need to reopen.
