### ISSUE TITLE
Training error: NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by kwea123** [NVIDIA/semantic-segmentation#29]
I used the `cityscapes_cv0_wideresnet38_nosdcaug.pth` as pretrained model and tried to train on cityscapes just to make sure the training works on cityscapes. The first 4 epochs were successful, but at some point from the fifth epoch, I got `Warning: NaN or Inf found in input tensor.` then the `train main loss` suddenly became nan (it was about 0.29) and the training failed from then.

Did you experience this? How to solve it?

Training options:
```
#!/usr/bin/env bash

    # Example on Cityscapes
     python -m torch.distributed.launch --nproc_per_node=2 train.py \
        --dataset cityscapes \
        --cv 0 \
        --arch network.deepv3.DeepWV3Plus \
        --snapshot ./ckpts/cityscapes_cv0_wideresnet38_nosdcaug.pth \
        --class_uniform_pct 0.5 \
        --class_uniform_tile 1024 \
        --max_cu_epoch 150 \
        --lr 0.001 \
        --lr_schedule scl-poly \
        --poly_exp 1.0 \
        --repoly 1.5  \
        --rescale 1.0 \
        --syncbn \
        --sgd \
        --crop_size 896 \
        --scale_min 0.5 \
        --scale_max 2.0 \
        --color_aug 0.25 \
        --gblur \
        --max_epoch 175 \
        --coarse_boost_classes 14,15,16,3,12,17,4 \
        --jointwtborder \
        --strict_bdr_cls 5,6,7,11,12,17,18 \
        --rlx_off_epoch 100 \
        --wt_bound 1.0 \
        --bs_mult 1 \
        --apex \
        --exp cityscapes_ft \
        --ckpt ./logs/ \
        --tb_path ./logs/
```

**Comment by bryanyzhu** [comment]
I didn't experience this before. It seems from the warning that your input has NaN or Inf. I suggest you do several try-catch blocks to locate where goes wrong. It maybe wrong in data loading part, or data transform part, or loss computation part. I need more information to debug into this.

**Comment by karansapra** [comment]
It might have something to do with 2 GPU. Could you try adjusting the learning rate? @bryanyzhu  @kwea123.

**Comment by chipkajb** [comment]
I ran into this problem as well. Lowering the learning rate sometimes helped, but not always. Sometimes, no matter how small I made the learning rate, I still ran into this issue. I got around it by just skipping the train main loss update whenever the train main loss was nan. In train.py, I replaced this line

`train_main_loss.update(log_main_loss.item(), batch_pixel_size)`

with this

```
if(torch.isnan(main_loss)):
    logging.info("Train main loss is nan. Skipping train main loss update")
else:
    train_main_loss.update(log_main_loss.item(), batch_pixel_size)
```

It seems to have resolved the problem for me.

**Comment by looong96** [comment]
@chipkajb 
Meet the same problem. Your solution didn't work for me, maybe because main_loss still nan. I want to replace nan with previous loss, but 'RuntimeError: Trying to backward through the graph a second time'. Please help me, I have been plagued by this for more than one week. nj-wl@foxmail.com or 1398714115@qq.com are my mail address, looking forward to your reply, thank you.

**Comment by chipkajb** [comment]
@looong96 
I am not sure how helpful I will be, but what do you mean my solution did not work for you? Is your main loss always nan? For me, my main loss would be nan very infrequently (maybe 1% of the time, I don't remember...). So I would just skip that iteration (with the if/else block of code I gave above) and then proceed normally. I'm sure it's not the best way to resolve the problem, but it was a quick workaround that worked for me.
According to your new error ('RuntimeError: Trying to backward through the graph a second time'), it looks like something else is going wrong. Something must be going wrong when you try to replace the nan loss value with the previous loss value. I was worried I would run into something like this, so that is why I simply skipped any iteration that produced a nan loss.

**Comment by denyunhero** [comment]
> I ran into this problem as well. Lowering the learning rate sometimes helped, but not always. Sometimes, no matter how small I made the learning rate, I still ran into this issue. I got around it by just skipping the train main loss update whenever the train main loss was nan. In train.py, I replaced this line
> 
> `train_main_loss.update(log_main_loss.item(), batch_pixel_size)`
> 
> with this
> 
> ```
> if(torch.isnan(main_loss)):
>     logging.info("Train main loss is nan. Skipping train main loss update")
> else:
>     train_main_loss.update(log_main_loss.item(), batch_pixel_size)
> ```
> 
> It seems to have resolved the problem for me.

Thanks, this works for me. It seems that the loss NaN causes the graident NaN and this NaN
