### ISSUE TITLE
Train in custom dataset

### ISSUE THREAD

**Issue by simaiden** [NVIDIA/semantic-segmentation#52]
Hi, first of all thanks for this amazing work. I want to train with this framework in a custom dataset, and I have some question about it:

- Is it possible to fine tuning the network with a reduced size dataset? In this case, Can I use the DeepWV3+ pretrained model replacing some layers? Some advice for this?
- It is enough 8gb VRAM memory to train this model?

Thanks in advance

**Comment by bryanyzhu** [comment]
Hi, thank you for using our code.

1. Yes, you can, as long as your dataset is similar to street scene segmentation. Depending on the size of your dataset, you may need to freeze some of the layers during fine-tuning. In my experience, if you have more than 1K training samples, you can basically do any fine-tuning you want. If you have less than 1K training samples, maybe you need to freeze the convolutional layers, and only train ASPP and segmentation head layers. And another thing is, using a small model backbone maybe helpful, such as using ResNeXt50 instead of WideResNet38. 

2. I will post the memory usage when I do the training, 
```
Setting A: Use DeepWV3+ with WideResNet38 backbone, batch size = 2 per GPU, and crop size 800x800, the memory usage is about 15.5G. 
Setting B: Use DeepWV3+ with ResNeXt50 backbone, batch size = 2 per GPU, and crop size 800x800, the memory usage is about 9.5G. 
```

So if you choose to use ResNeXt50 backbone and reduce the crop size a bit or freeze part of the layers, 8GB memory should be enough.

**Comment by simaiden** [comment]
Thanks for the quick reply

1. I have another question about this. In the script `train_kitti_WideResNet38.sh` is this already doing fine tuning? I guess so but it seems doesn't freeze the layers.
2.   I've downloaded the KITTI dataset and did an experimental training and seems no problem with VRAM usage, in fact the `nvidia-smi` command show me 4.5Gb used no matter the epoch running. Is  this good or am i doing something wrong?

Many thanks!

**Comment by bryanyzhu** [comment]
Hi, 

1. Yes, it is fine-tuning, and we don't freeze the layers. We tried freeze the layers but didn't observe improvements. The reason is maybe KITTI is too similar with Cityscapes. They are both images captured from Germany cities. So it doesn't matter whether you freeze the layers or not.

2. Yes, it is good. Because for KITTI, we only use a crop size of 360, which reduces the memory usage quite a bit. In my experience, reducing crop size is the most effective method to reduce memory usage, freezing layers is less effective.

**Comment by simaiden** [comment]
Many thanks for the help @bryanyzhu ! I will close this issue for now
