### ISSUE TITLE
为什么背景类没参与到loss计算？

### ISSUE THREAD

**Issue by hongdayu** [NVIDIA/semantic-segmentation#9]
我没弄错的话，背景类没参与交叉熵计算。请教下，这样做的原因是什么？

**Comment by bryanyzhu** [comment]
因为背景类并不在evaluation的范围之内, 所以训练的时候也不需要参与loss计算. 你可以具体看下这个[文件](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py), 里面所有背景类的trainID都是255, 而且ignoreInEval这个选项都是True. 所以属于don't care的类别.

**Comment by hongdayu** [comment]
> 因为背景类并不在evaluation的范围之内, 所以训练的时候也不需要参与loss计算. 你可以具体看下这个[文件](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py), 里面所有背景类的trainID都是255, 而且ignoreInEval这个选项都是True. 所以属于don't care的类别.

感谢大佬回复。那么预测错误的背景pixel如何处理？

**Comment by hongdayu** [comment]
我意思是 我训练自己的数据集，现在训练过程观测logs里面的best image,发现背景pixel FN很高，也就是背景pixel预测到其他类，请问最后能收敛时，还有这个现象么。

**Comment by bryanyzhu** [comment]
如果你关心背景pixel的话, 那每个loss function都有一个这个参数, 叫ignore_index (比如[这里](https://github.com/NVIDIA/semantic-segmentation/blob/master/loss.py#L23)). 目前设的是255, 所以所有的背景类都不计算loss. 你可以设成none或者别的数值就好了, 这样相当于背景也是一类, 最后FN就会好很多.

**Comment by hongdayu** [comment]
> 如果你关心背景pixel的话, 那每个loss function都有一个这个参数, 叫ignore_index (比如[这里](https://github.com/NVIDIA/semantic-segmentation/blob/master/loss.py#L23)). 目前设的是255, 所以所有的背景类都不计算loss. 你可以设成none或者别的数值就好了, 这样相当于背景也是一类, 最后FN就会好很多.

好的 感谢

**Comment by bryanyzhu** [comment]
To summarize this issue in English, it has two questions. 

### 1. Why background class is not involved in loss computation? 
Since background class is not considered during evaluation, we don't compute its loss during training. You can check more details at [here](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py). All background classes have a single `trainID` as 255, and its `ignoreInEval ` are set to True. Basically, they belong to `don't care` class.

### 2. What if we want to include background into training? 
Every loss function has a argument, named `ignore_index` (e.g., [here](https://github.com/NVIDIA/semantic-segmentation/blob/master/loss.py#L23)). Right now, `ignore_index` is set to 255, so the background class is not involved for loss computation. If you want to consider background as a class, simply set `ignore_index` to None or other values.

**Comment by songyadong106** [comment]
@hongdayu，可以问你一些loss的问题吗？
